on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Read file content
#        id: read-file
#        run: |
#          file_content=$(cat ${{ github.workspace }}/summary.md)
#          echo "FILE_CONTENT=$file_content" >> $GITHUB_OUTPUT
#      - name: test
#        run: echo ${{ steps.read-file.outputs.FILE_CONTENT }}
      - name: List files
        id: listFiles
        run: |
          jsonContent="$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$OWNER/$REPO/pulls/$PULL_NUMBER/files)"
          echo "JSON_CONTENT="$jsonContent >> "$GITHUB_OUTPUT"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
            PULL_NUMBER: ${{ github.event.pull_request.number }}
      - name: Showing content
        uses: actions/github-script@v6
        with:
          script: |
            const content = ${{steps.listFiles.outputs.JSON_CONTENT}};
            const fileLinesMap = new Map();
            content.forEach(diff => {
              const { filename, patch } = diff;

              const patchLines = patch.match(/@@ -(\d+),(\d+) \+\d+,\d+ @@/);
              if (patchLines) {
                const startLine = parseInt(patchLines[1], 10);
                endLine = startLine + parseInt(patchLines[2], 10) - 1;
                if(endLine < 0)
                  endLine = 0
                fileLinesMap.set(filename, { startLine, endLine });
              }
            });
            console.log(fileLinesMap);
      - uses: actions/github-script@v6
        env:
          DATA: ${{steps.listFiles.outputs.JSON_CONTENT}};
        with:
          script: |
            const script = require('./.github/workflows/reports-to-comments.js');
            script({github, context});

