on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Read file content
#        id: read-file
#        run: |
#          file_content=$(cat ${{ github.workspace }}/summary.md)
#          echo "FILE_CONTENT=$file_content" >> $GITHUB_OUTPUT
#      - name: test
#        run: echo ${{ steps.read-file.outputs.FILE_CONTENT }}
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const execSync = require('child_process').execSync;
            const files = execSync('find reports/ -type f').toString().split('\n').filter(Boolean);
            const comments = [];
            files.forEach(file => {
              const body = fs.readFileSync(file, 'utf8');
              const path = '.github/workflows/test.yml';
              const side = "RIGHT";
              const start_line = 8;
              const start_side = "RIGHT";
              const line = 11;
              const comment = {
                body: body,
                path: path,
                side: side,
                start_line: start_line,
                start_side: start_side,
                line: line
              };
              comments.push(comment);
            });
            github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                commit_id: context.payload.pull_request.head.sha,
                comments: comments
              });

