on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Read file content
#        id: read-file
#        run: |
#          file_content=$(cat ${{ github.workspace }}/summary.md)
#          echo "FILE_CONTENT=$file_content" >> $GITHUB_OUTPUT
#      - name: test
#        run: echo ${{ steps.read-file.outputs.FILE_CONTENT }}
      - name: List files
        id: listFiles
        run: |
          jsonContent="$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$OWNER/$REPO/pulls/$PULL_NUMBER/files)"
          echo "JSON_CONTENT="$jsonContent >> "$GITHUB_OUTPUT"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OWNER: ${{ github.repository_owner }}
            REPO: ${{ github.event.repository.name }}
            PULL_NUMBER: ${{ github.event.pull_request.number }}
      - name: Showing content
        uses: actions/github-script@v6
        with:
          script: |
            const content = ${{steps.listFiles.outputs.JSON_CONTENT}};
            const updatedContent = content.toString.replace(/\n/g, '\\n');
            console.log(updatedContent);
            const diffArray = JSON.parse(updatedContent);
            const fileLinesMap = new Map();

            diffArray.forEach(diff => {
              const { filename, patch } = diff;

              const patchLines = patch.match(/@@ -(\d+),(\d+) \+\d+,\d+ @@/);
              if (patchLines) {
                const startLine = parseInt(patchLines[1], 10);
                const endLine = startLine + parseInt(patchLines[2], 10) - 1;

                fileLinesMap.set(filename, { startLine, endLine });
              }
            });
            console.log(fileLinesMap);

#      - name: Showing content
#        uses: actions/github-script@v6
#        with:
#          script: |
#            const content = ${{ steps.listFiles.outputs.JSON_CONTENT}};
#            console.log(content);
#            console.log("HOLA");
#            const diffArray = JSON.parse(content);
#            const fileLinesMap = new Map();
#
#            diffArray.forEach(diff => {
#              const { filename, patch } = diff;
#
#              const patchLines = patch.match(/@@ -(\d+),(\d+) \+\d+,\d+ @@/);
#              if (patchLines) {
#                const startLine = parseInt(patchLines[1], 10);
#                const endLine = startLine + parseInt(patchLines[2], 10) - 1;
#
#                fileLinesMap.set(filename, { startLine, endLine });
#              }
#            });
#            console.log(fileLinesMap);
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const execSync = require('child_process').execSync;
            const files = execSync('find iac-suggestions/ -type f').toString().split('\n').filter(Boolean);
            const comments = [];
            files.forEach(file => {
              const filename = file.substring(file.lastIndexOf("/") + 1, file.lastIndexOf("."));
              const info = filename.split("-");
            
              const body = fs.readFileSync(file, 'utf8').split("\n");
              const path = body.shift();
              const side = "RIGHT";
              const start_line = parseInt(info[info.length - 2]);
              const start_side = "RIGHT";
              const line = parseInt(info[info.length - 1]);
              const comment = {
                body: body.join("\n"),
                path: path,
                side: side,
                start_line: start_line,
                start_side: start_side,
                line: line
              };
              comments.push(comment);
            });
            github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                commit_id: context.payload.pull_request.head.sha,
                event: 'COMMENT',
                comments: comments
              });

