on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Read file content
#        id: read-file
#        run: |
#          file_content=$(cat ${{ github.workspace }}/summary.md)
#          echo "FILE_CONTENT=$file_content" >> $GITHUB_OUTPUT
#      - name: test
#        run: echo ${{ steps.read-file.outputs.FILE_CONTENT }}
#      - uses: actions/github-script@v6
#        with:
#          script: |
#            github.rest.pulls.createReviewComment({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              pull_number: context.issue.number,
#              body: "illo yo k se, espabila",
#              commit_id: context.payload.pull_request.head.sha,
#              diff_hunk: "@@ -3,4 +3,4 @@     -\"name\": \"guion\",; -\"restrict-level\": \"director\; -\"name\": \"gon\",; -\"restrict-level\": \"dctor\" ",
#              path: 'src/application.conf',
#              start_line: 1,
#              line: 2,
#              start_side:'RIGHT',
#              headers: {
#                'X-GitHub-Api-Version': '2022-11-28'
#              }
#            });
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install @actions/github octokit

      - name: Create Comment
        run: |
          const { Octokit } = require("@octokit/rest");
          const fs = require("fs");
          
          const octokit = new Octokit({
            auth: process.env.GITHUB_TOKEN
          });
          
          const commentBody = `Suggestion:
          \`\`\`diff
          @@ -3,4 +3,4 @@      def main():
          -    print(greeting("Alice")) 
          +    printlnal
          \`\`\``;
          
          octokit.issues.createComment({
            context.repo.owner,
            context.repo.repo,
            issue_number: context.issue.number,
            body: commentBody,
            commit_id: process.env.GITHUB_SHA,
            path: 'src/application.conf',
            position: 5
          });
