on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read file content
        id: read-file
        run: | 
          file_content=$(cat ${{ github.workspace }}/summary.md)
          echo "::set-output name=fileContent::$file_content"
      - uses: actions/github-script@v6
        with:
          script: |
            const body = '${{ steps.read-file.outputs.fileContent }}'
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })